[program:proxmox-backup-proxy]
command=/etc/supervisor/scripts/proxmox-backup-proxy.sh
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
